@startuml
'https://plantuml.com/class-diagram
left to right direction

class Die {
Type or amount of sides
}
Die : roll()

class Player{
Name
Score
}
Player : setPlayerScore()
Player : getPlayerScore()
Player : setPlayerName()
Player : getPlayerName()

class DieCup {
amount of dice
}
DieCup : ThrowDice()

class PointSystem {
Player 1
Player 2
}

class GameController {
DieCup
PointSystem
}
GameController : main()

class GUI


GameController -- GUI
GameController -- DieCup
Die -- DieCup
Player --PointSystem
PointSystem -- GameController


@enduml