@startuml
'https://plantuml.com/use-case-diagram

agent Terning
:Spil System: as Game
:Point System: as Points


User --> (Opret Spillerer)
User --> (Resultat Vises)
User --> (Kast Terninger)

Terning --> (Kast Terninger)
Terning --> (Resultat Vises)

Game --> (Opret Spillerer)
Game --> (Vise Ny Score)
Game --> (Udråbe Vinder)

Points --> (Resultat Vises)
Points --> (Udregne Ny Score)



@enduml